import turtle as t
import math
t.color("gray")
t.shape("turtle")
walls_width = int(input("ширина стен "))
walls_height = int(input("высота стен "))
walls_color = input("цвет стен в hex ")
door_width = int(input("ширина двери "))
door_height = int(input("высота двери "))
door_color = input("цвет двери в hex ")
roof_height = int(input("высота крыши "))
roof_side = math.sqrt(roof_height ** 2 + (walls_width / 2) ** 2)
roof_angle = math.degrees(math.atan(roof_height / (walls_width / 2)))
roof_color = input("цвет крыши в hex ")
t.speed(0)
t.setheading(180)
t.fd(walls_width / 2)
t.left(90)
t.fd((walls_height + roof_height) / 2)
t.setheading(360)
t.setposition((walls_width / 2) * -1, (walls_height + roof_height) / 2 * -1)
t.fillcolor(walls_color)
t.begin_fill()
for i in range(2):
    t.fd(walls_width)
    t.left(90)
    t.fd(walls_height)
    t.left(90)
t.end_fill()
t.fillcolor(door_color)
t.begin_fill()
t.fd(walls_width / 2 - door_width / 2)
for i in range(2):
    t.fd(door_width)
    t.left(90)
    t.fd(door_height)
    t.left(90)
t.end_fill()
t.fillcolor(roof_color)
t.left(180)
t.fd(walls_width / 2 - door_width / 2)
t.right(90)
t.fd(walls_height)
t.right(90)
t.begin_fill()
t.left(roof_angle)
t.fd(roof_side)
t.right(roof_angle * 2)
t.fd(roof_side)
t.setheading(180)
t.fd(walls_width)
t.end_fill()
t.done()